[project]
name = "cat-and-dog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.10"
dependencies = [
    "flask>=3.0.3",
    "keras>=3.6.0",
    "numpy>=2.0.2",
    "pillow>=11.0.0",
    "tensorflow>=2.18.0",
]

[dependency-groups]
dev = [
    "mypy>=1.13.0",
    "pytest>=8.3.3",
    "ruff>=0.7.1",
]
