global:
  scrape_interval: 10s
scrape_configs:
  - job_name: prometheus-server-itself
    static_configs:
      - targets:
        - localhost:9090
  - job_name: flask-app
    static_configs:
      - targets:
        - flask:5000      
